CREATE DATABASE IF NOT EXISTS <your_db_name> CHARACTER SET utf8mb4 COLLATE utf8mb4_turkish_ci;
USE <your_db_name>;

DROP USER IF EXISTS '<your_db_user>'@'127.0.0.1';

FLUSH PRIVILEGES;

SET SQL_SAFE_UPDATES = 0;

CREATE TABLE libraries(id INT AUTO_INCREMENT PRIMARY KEY,
libName VARCHAR(20),
libPassword VARCHAR(255));




